name: pos_system
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentatioyn/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.54+169

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  package_info: ^2.0.2
  shared_preferences: any
  intl: ^0.18.0
  url_launcher: ^6.1.10
  google_fonts: ^4.0.3
  devicelocale: ^0.6.0
  provider: ^6.0.5
  collapsible_sidebar:
    git:
      url: https://github.com/tkygcw/flutter_collapsible_sidebar.git
  quantity_input: ^1.0.2
  grouped_list: ^5.1.2
  side_navigation: ^1.0.4
  flutter_material_color_picker: ^1.1.0+2
  flutter_login: ^5.0.0
  sqflite: ^2.4.1
  fluttertoast: ^8.2.1
  dropdown_button2: ^2.3.9
  page_transition: ^2.0.9
  animations: ^2.0.7
  path_provider: ^2.0.14
  custom_pin_screen:
    git:
      url: https://github.com/tkygcw/custom_pin_screen.git
  virtual_keyboard_multi_language: ^1.0.3
  group_radio_button: ^1.3.0
  confirm_dialog: ^1.0.1
  image_picker: ^0.8.7
  path: ^1.8.2
  checkbox_grouped: ^2.0.0
  collection: ^1.17.0
  flutter_native_image: ^0.0.6+1
  esc_pos_printer:
    git:
      url: https://github.com/tkygcw/esc_pos_printer.git
  flutter_usb_printer:
    git:
      url: https://github.com/tkygcw/flutter_usb_printer.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  reorderable_grid_view: ^2.2.6

  lan_scanner: ^4.0.0
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  xml2json: ^5.3.6
  firebase_messaging: ^15.1.2
  firebase_core: ^3.5.0
  flutter_local_notifications: ^17.2.2
  presentation_displays: ^0.2.3
  app_settings: ^5.1.1
  location: ^4.4.0
  internet_connection_checker: ^1.0.0+1
  syncfusion_flutter_datepicker: ^22.2.12
  pdf: 3.11.0
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  file: 6.1.4
  barcode_scan2: ^4.2.4
  rxdart: ^0.27.7
  dotted_line: ^3.2.0
  esc_pos_utils_plus: ^2.0.2
  carousel_slider: ^5.0.0
  another_flushbar: ^1.12.30
  flash: ^3.0.5
  version: ^3.0.2
  f_logs:
    git:
      url: https://github.com/tkygcw/Flogs.git
  flutter_file_dialog: ^3.0.2
  connectivity_plus: ^6.0.3
  network_info_plus: ^4.1.0+1
  printing: ^5.13.1
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0
  gms_check: ^1.0.2
  archive: ^3.5.1
  async_queue: ^2.0.0
  awesome_snackbar_content: ^0.1.3
  pdf_widget_wrapper: ^1.0.4
  circular_menu: ^4.0.0
  cloud_firestore: ^5.4.2
  toastification: ^2.3.0
  assets_audio_player: ^3.1.1
  store_checker: ^1.6.0
  print_bluetooth_thermal: ^1.1.1
  permission_handler: ^11.3.1
  file_picker: ^8.1.7
  decimal: ^3.2.1

dependency_overrides:
  image_picker_android: 0.8.6+6
  intl: 0.18.0
  image: ^4.1.3
  win32: 5.5.4
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  image_path: "drawable/logo.jpg"
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/  tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - language/
    - drawable/
    - audio/
    - shorebird.yaml
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HeiSASC
      fonts:
        - asset: font/simply_chinese.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
